### PR TITLE
Added check for some old browsers

### PR DESCRIPTION
**Pull request by talyuk**

### CODE REVIEW

**Review by jfirebaugh — COMMENTED** [review]
Thanks @talyuk. However, we need to avoid using `eval` because it will trip content security policy restrictions. Can you make this a test for the existence of `ArrayBuffer.isView` instead, as discussed in https://github.com/mapbox/mapbox-gl-js/issues/6669?

**Comment by talyuk** [comment]
@jfirebaugh There is an unexpected behavior: ArrayBuffer.isView is not undefined, it returns a function. WebGL is supported. But blob file causes an error (https://github.com/mapbox/mapbox-gl-js/issues/6669). 
The only solution I found is to check for `let`

**Comment by jfirebaugh** [comment]
Are you sure? The title of the bug is "Object function ArrayBuffer() { [native code] } has no method 'isView'", which is an error message indicating that `isView` does not exist on `ArrayBuffer`.

**Comment by talyuk** [comment]
@jfirebaugh look


I have no ideas how to deal with it

**Comment by jfirebaugh** [comment]
Very strange. Could it be that `ArrayBuffer.isView` is available on the main context but not in Web Workers?

**Comment by talyuk** [comment]
It makes sense. Have you an idea how to resolve it?

**Comment by jfirebaugh** [comment]
I'm out of ideas -- I think you'll need to dig in further.

**Comment by jfirebaugh** [comment]
Added a naive test for `ArrayBuffer.isView` in https://github.com/mapbox/mapbox-gl-supported/commit/8426b3a7eff695b0efeb6adaabb3396bce11e0fd. If there's more to this than that, we'll need someone with access to an affected environment to investigate.

**Pull request closed without merging**
